config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    match 'login' => 'devise/sessions#new', via: :get
    match 'login' => 'devise/sessions#create', via: :post
    match 'logout' => 'devise/sessions#destroy', via: :get
    match 'signup' => 'devise/registrations#new', via: :get
    match 'signup' => 'devise/registrations#create', via: :post
  end

  resources :restaurants do
    get 'menus/home' => 'menus#home'
    resources :menus do
      resources :menu_photos
    end
    resources :categories
    resources :comments
  end

  resources :user_sym_points
  
  root 'restaurants#index'
  post '' => 'welcome#login'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :category

	has_many :menu_photos, dependent: :destroy
  has_many :menu_videos, dependent: :destroy
  has_many :menu_translations, dependent: :destroy

	def photos
  	self.menu_photos.order('seq')
  end

  def create_photos(photos)
    seq = self.photos.count

    photos.each do |p|
      seq = seq + 1
      self.menu_photos.create(:photo=>p, :seq=>seq)
    end
  end

  def main_photo(type)
    if self.menu_photos.order('seq').first
      self.menu_photos.order('seq').first.url(type)
    else
      "/assets/logo/restaurant#{RestaurantPhoto::PHOTO_STYLE[type]}.png"
    end
  end

  def videos
    self.menu_videos.order('seq')
  end

  def create_videos(videos)
    seq = self.videos.count

    videos.each do |v|
      seq = seq + 1
      self.menu_videos.create(:video=>v, :seq=>seq)
    end
  end

  def main_video(type)
    if self.menu_videos.order('seq').first
      self.menu_videos.order('seq').first.url(type)
    else
      "/assets/logo/restaurant#{RestaurantPhoto::PHOTO_STYLE[type]}.png"
    end
  end

  def translations
    self.menu_translations.order('locale')
  end

  def locale_translation(locale)
    self.menu_translations.find_by_locale(locale)
  end

  def create_translations(langs)
    locale = 0

    langs.each do |l|
      self.menu_translations.create(:name=>l, :locale=>locale)
      locale = locale + 1
    end
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_restaurant
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def home
  end

  def index
    @menus = @restaurant.menus.all
    @categories = @restaurant.categories.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    if @menu.category_id
      @category = @restaurant.categories.find(@menu.category_id)
    end
  end

  # GET /menus/new
  def new
    @menu = @restaurant.menus.new
    @categories = @restaurant.categories.all
  end

  # GET /menus/1/edit
  def edit
    @categories = @restaurant.categories.all
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = @restaurant.menus.new(menu_params)

    respond_to do |format|
      if @menu.save
        unless params[:menu_videos].blank?
          @menu.create_videos(params[:menu_videos])
        end
        unless params[:menu_translations].blank?
          @menu.create_translations(params[:menu_translations])
        end
        unless params[:menu_photos].blank?
          @menu.create_photos(params[:menu_photos])
          # format.html { render :action => "edit_photo" }
        end
        format.html { redirect_to [@menu.restaurant, @menu], notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        unless params[:menu_videos].blank?
          @menu.create_videos(params[:menu_videos])
        end
        unless params[:menu_translations].blank?
          @menu.create_translations(params[:menu_translations])
        end
        unless params[:menu_photos].blank?
          @menu.create_photos(params[:menu_photos])
          # format.html { render :action => "edit_photo" }
        end
        format.html { redirect_to [@menu.restaurant, @menu], notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to [@menu.restaurant, @menu], notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = @restaurant.menus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :price, :description, :category_id, :menu_translations, :price_usd, :price_jpy, :price_cny)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_change_lang.html.erb
<script type="text/javascript">
	window.onload = change_lang(); 

  function change_lang(){
  	var current_session_language = '<%= I18n.locale %>';
  	var source_language = 'KPW';
    var target_language;

    console.log("change_lang_test");

  	if(current_session_language == 'en')	{
  		target_language = 'USD';
  	}else if(current_session_language == 'ja')	{
  		target_language = 'JPY';
  	}else if(current_session_language == 'ko')	{
  		target_language = 'KPW';
  	}else if(current_session_language == 'ch') {
      target_language = 'CNY';
    }

  	console.log(current_session_language + '->' + target_language);

    if(target_language == 'KOR')	{
    	document.getElementById("locale_price").innerHTML = '';
    	translate(target_language);
    	return;	
    }
    
    translate(target_language);

    getRate(source_language, target_language);
  }

  // 메뉴명 번역 
  function translate(to)	{
		var menu_name = document.getElementById("menu_name");

    console.log(document.getElementById("menu_name"));

		if(to == 'KOR') {
			menu_name.innerHTML = "<%= @menu.name %>";
		}else if(to == 'USD')	{
			menu_name.innerHTML = " / <%= @menu.locale_translation(0).name %>";
		}else if(to == 'JPY')	{
			document.getElementById("menu_name").innerHTML = " / <%= @menu.locale_translation(1).name %>";
		}else if(to == 'CNY')	{
			menu_name.innerHTML = " / <%= @menu.locale_translation(2).name %>";
		}
	}

  <!-- 환율 변환 -->
  function getRate(from, to){
    if(to =='KPW') {
      return;
    }
    
    if(to == 'USD') {
      var locale = '$';
      <% if(@menu.price_usd.present?) %>
        var money = <%= @menu.price_usd %>;
      <% end %>
    }else if(to == 'JPY')  {
      var locale = 'Ұ';
      <% if(@menu.price_jpy.present?) %>
        var money = <%= @menu.price_jpy %>;
      <% end %>
    }else if(to == 'CNY')  {
      var locale = 'CN¥';
      <% if(@menu.price_cny.present?) %>
        var money = <%= @menu.price_cny %>;
      <% end %>
    }
    
    document.getElementById("locale_price").innerHTML = " &nbsp; &nbsp; &nbsp; / &nbsp; &nbsp; &nbsp;" + locale + " " + money;
  }
  
</script>

app/views/menus/_detail.html.erb
<script type="text/javascript"> 
  $('.menu-item').click(function(){
    var id = $(this).data('id');
    $.ajax({
      // url: "/restaurants/" + restaurant_id + "/menus/" + menu_id
      url: "/menus/" + id + ".json",
      dataType: "JSON",
      success: function(d){
        renderDetail(d);
      },
      error: function(e){
        console.log(e);
      }
    })
  });

  function renderDetail(d){
    var details = $("#detailTemplate").html();
    var detailsTemplate = Handlebars.compile(details);
    var detailsHtml = detailsTemplate(d);

    console.log(d);

    $('#detail_tap').html(detailsHtml);
    $('.section-tab.active').removeClass('active').removeClass('in');
    $('#detail_tap').addClass('active').addClass('in');
  }
</script>

<script id="detailTemplate" type="text/x-handlebars-template">
  <h4 class="section-title">
    {{menu.name}}

    <small>{{menu.subname}}</small>

    <span class="detail-prices pull-right">
      {{#if submenus}}
        {{#each submenus}}
          <span class="price-item">
            {{name}} - <span class="amount">{{addCommas price}}</span>
          </span>
        {{/each}}
      {{else}}
        <span class="amount">{{addCommas menu.price}}</span>
      {{/if}}
    </span>
  </h4>

  <div class="detail-photo">
    {{#if photos}}
      <div id="carousel-for-detail" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          {{#each photos}}
            <li data-target="#carousel-for-detail" 
              data-slide-to="{{@index}}" 
              {{#isEqual @index 0}}
              class="active"
              {{/isEqual}}
              ></li>
          {{/each}}
        </ol>

        <div class="carousel-inner" role="listbox">
          {{#each photos}}
            <div class="item {{#isEqual @index 0}}active{{/isEqual}}">
              <img src="{{large}}" alt="{{../menu.name}}">
            </div>
          {{/each}}
        </div>

        <a class="left carousel-control" href="#carousel-for-detail" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-for-detail" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    {{else}}
      <img src="{{photo}}" alt="{{menu.name}}" class="img-responsive"/>
    {{/if}}
  </div>

  <div class="description">
    {{menu.description}}
  </div>
</script>

app/views/menus/_form.html.erb
<%= render 'form_translation' %>

<%= simple_form_for([@restaurant, @menu], :html => {:multipart => true}) do |f| %>
  <%= f.error_notification %>

<div class="panel-body">
  <div class='row'>
    <div class='col-md-2 menu-form-label'>
      <label>메뉴명</label>
    </div>
    <div class='col-md-6 col-xs-8 menu-form-input'>
      <%= f.text_field :name, :class=>'string optional form-control' %>
    </div>
    <div class='col-md-4 col-xs-4'>
      <button type="button" class="btn btn-primary" id="search" data-toggle="modal" data-target="#myModal">
        번역
      </button>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-2 menu-form-label'>
      <label>메뉴 카테고리</label>
    </div>
    <div class='col-md-4 menu-form-input'>
      <%= f.collection_select :category_id, @categories.order(:name), :id, :name, {include_blank: '카테고리를 선택해주세요'}, {class: 'form-control'} %>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-2 menu-form-label'>
      <label>가격</label>
    </div>
    <div class='col-md-4 col-xs-8 menu-form-input'>
      <input class="numeric integer optional form-control" type="number" step="10" name="menu[price]" id="menu_price">
    </div>
    <div class='col-md-4 col-xs-4'>
      <button type="button" class="btn btn-primary" id="exchange" data-toggle="modal" data-target="#mModal">
        환율적용
      </button>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-2 menu-form-label'>
      <label>사진</label>
    </div>
    <div class='col-md-4 menu-form-input'>
      <input id="uploadImage" class="form-control file" type="file" name="menu_photos[]" label="affe" onchange="PreviewImage();" accept="image/*" capture="camera" multiple>
    </div>
  </div>
    
  <div class='visible-xs row'>
    <div class='col-md-2 menu-form-label'>
      <label>카메라</label>
    </div>
    <div class='col-md-6'>
      <div id='container_input_camera'>
        <img src="/assets/camera_icon.png">
        <input id="uploadImage_by_camera" class="form-control file" type="file" name="menu_photos[]" onchange="PreviewImage();" accept="image/*" capture="camera">
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-2 menu-form-label'>
      <label>비디오</label>
    </div>
    <div class='col-md-4 menu-form-input'>
      <input id="uploadVideo" class="form-control file" type="file" name="menu_videos[]" onchange="PreviewVideo();" multiple>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-2 menu-form-label'>
      <label>설명</label>
    </div>
    <div class='col-md-9 menu-form-input'>
      <textarea rows="5" class="text optional form-control" name="menu[description]" id="menu_description"><%= @menu.description %></textarea>
    </div>
  </div>

  <%= render 'form_exchange' %>

  <div class='row'>
    <div class='col-md-2 menu-form-label'>
    </div>
    <div class='col-md-9 menu-form-input'>
      <%= f.button :submit, :value=>t(:save_button), :class=>'btn btn-primary' %>
    </div>
  </div>

    <% if !@menu.photos.empty? %>
      <div class="row">
        <% @menu.photos.each do |p| %>
          <div class="col-md-4 restaurant-edit-photo">
            <%= image_tag p.photo.url(:medium), :class=>"img-responsive" %>
          </div>
        <% end %>
      </div>
    <% end %>

    <div id="menu-photos-wrapper" class="row">
    </div>

</div>
<!-- Panel Body - End -->


	<div id='trans_result_input' style="display:none;">
		<input id='menu_menu_translations_1' name='menu_translations[]'>
		<input id='menu_menu_translations_2' name='menu_translations[]'>
		<input id='menu_menu_translations_3' name='menu_translations[]'>
	</div>

<% end %>

<script type="text/javascript">
  function PreviewImage() {
    var reader = new FileReader();
    var files = document.getElementById("uploadImage").files;

    function readFile(index){
      if(index >= files.length) return;

      var file = files[index];
      reader.onload = function(e){
        $('#menu-photos-wrapper').append("<div class='col-md-3'><img id='wrapper_image_"+ index +"' class='img-responsive' src='" + e.target.result + "'/></div>");
        readFile(index + 1);
      }
      reader.readAsDataURL(file);
    }

    if(files.length > 0){
      readFile(0);
    }
  };

</script>

<script type="text/javascript">
  function crop_image(image_id) {
    var image = document.getElementById("wrapper_image_" + image_id);

    console.log("test : " + image_id);

    $('#container_input_camera').append("<div class='col-md-3'><img class='img-responsive' src='" + image.src + "'/>");
  }
</script>

<!-- Jcrop -->
<script type="text/javascript">
	$(function() {
		// body...
		$('.img-responsive').Jcrop();
	});
</script>

app/views/menus/_form_translation.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $('#search').on('click',function(){
      document.getElementById('trans_result_table').style.display = 'block';

      var keyword = document.getElementById("menu_name").value;
      
      var googleApiKey = "AIzaSyD6Zl9LOdgemtJ0tSSL0Mao1hJYvRwq_0w";
      var url = "http://117.17.158.133:9200/tour/food/_search?size=100&q=Korean:" + keyword + "*" + "&sort=Korean:asc";

      $.ajax({ 
        beforeSend: function(xhrObj){
              xhrObj.setRequestHeader("Content-Type","application/json");
              xhrObj.setRequestHeader("Accept","application/json");
        },
        type: 'GET', 
        contentType: "application/json; charset=utf-8",
        url: url, 
        crossDomain: true,
        dataType : "json", 
        success: function(data) { 
          console.log(data);

          var i;
          var out = [];

          var eng, jn, cn;

          if(data.hits.hits.length == 0){
            console.log("Google Translator");

            $.getJSON( "https://www.googleapis.com/language/translate/v2?key=" + googleApiKey + "&q=" + encodeURIComponent(keyword) + "&source=ko&target=en", function( data ) {

              eng = data.data.translations[0].translatedText;

            });

            $.getJSON( "https://www.googleapis.com/language/translate/v2?key=" + googleApiKey + "&q=" + encodeURIComponent(keyword) + "&source=ko&target=ja", function( data ) {

              jn = data.data.translations[0].translatedText;
        
            });

            $.getJSON( "https://www.googleapis.com/language/translate/v2?key=" + googleApiKey + "&q=" + encodeURIComponent(keyword) + "&source=ko&target=zh-CN", function( data ) {

              cn = data.data.translations[0].translatedText;

              out += "<tr onclick='saveLang(this)'><td>" +
                     keyword +
                     "</td><td>" +
                     eng +
                     "</td><td>" +
                     jn +
                     "</td><td>" +
                     cn +
                     "</td></tr>";  
              document.getElementById("trans_result_tbody").innerHTML = out;
            });
          }else{
            for (i = 0; i < data.hits.hits.length; i++) {
              out += "<tr onclick='saveLang(this)'><td>" +
                     data.hits.hits[i]._source.Korean +
                     "</td><td>" +
                     data.hits.hits[i]._source.English +
                     "</td><td>" +
                     data.hits.hits[i]._source.Japanese_W +
                     "</td><td>" +
                     data.hits.hits[i]._source.Chinese_R +
                     "</td></tr>";
            }
            document.getElementById("trans_result_tbody").innerHTML = out;
          }               
        },
        error: function(err){
            console.log(err);
        }
      });  
    })
  });

  function saveLang(lang) {
    var localLangs = lang.getElementsByTagName('td');
    var rows = document.getElementsByTagName("tr");   

    for(i = 0; i < rows.length; i++){           
      rows[i].style.backgroundColor = "white"
    }
    lang.style.backgroundColor = "#f06d71"

    console.log(localLangs[0].innerText);

    var langs = [];

    var en = localLangs[1].innerText;
    var jn = localLangs[2].innerText;
    var cn = localLangs[3].innerText;

    document.getElementById('menu_menu_translations_1').value = en;
    document.getElementById('menu_menu_translations_2').value = jn;
    document.getElementById('menu_menu_translations_3').value = cn;

    // document.getElementById('trans_result_table').style.display = 'none';
  }
</script>
  
<!-- Translation Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
          번역 메뉴명 선택
        </h4>
      </div>
      <div class="modal-body">
        <table class="table" id='trans_result_table' style='display:none'>
          <thead>
            <tr>
              <th>Korean</th>
              <th>English</th>
              <th>Japanese</th>
              <th>Chinese</th>
            </tr>
          </thead>
          <tbody id="trans_result_tbody"></tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/menus/_menu_item.html.erb
<%= link_to([menu.restaurant, menu]) do %>
  <div class="col-md-4 menu-item" data-id="<%= menu.id %>">
    <div class="menu-item-wrapper">
      <%= image_tag menu.main_photo(:large), :class=>"img-responsive" %>
      <div class="menu-description">
        <div class="menu-name">
          <%= menu.name %>
        </div>
        <div class="menu-price">
          <%= number_to_currency(menu.price, :unit => "₩ ", precision: 0, format: '%u%n') %>
        </div>
      </div>
    </div>

    <% if user_signed_in? && @restaurant.user_id == current_user.id%>
      <div style='display:none;'>
        <li><%= link_to '수정', edit_restaurant_menu_path(menu.restaurant, menu) %></li>
        <li><%= link_to '삭제', [menu.restaurant, menu], method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </div>
    <% end %>
  </div>
<% end %>

app/views/menus/_photo.html.erb
<% unless @menu.photos.empty? %>
	<div id="carousel-example-generic" class="carousel carousel-fade slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	  	<% @menu.photos.each_with_index do |photo, index| %>
	  		<li data-target="#carousel-example-generic" 
	  			data-slide-to="<%= index %>"
	  			 class="<%= "active" if index == 0 %>"></li>
	  	<% end %>
	  </ol>

	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox">
	  	<% @menu.photos.each_with_index do |photo, index| %>
	  		<div class="item <%= "active" if index == 0 %>">
	  			<%= image_tag photo.url(:large) %>
	  		</div>
	  	<% end %>
    </div>

	  <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
<% else %>
	<div class="resturant-empty-photo">
		<%= image_tag @menu.main_photo(:large), :style=>"margin-bottom: 20px;" %>
		<span><%= t :restaurant_empty_photo %></span>
	</div>
<% end %>

app/views/menus/_video.html.erb
<% unless @menu.videos.empty? %>
	<% @menu.videos.each_with_index do |video, index| %>
		<div class="item <%= "active" if index == 0 %>">
				<video src="<%=video.video.url(:medium) %>" width="100%" height="auto" controls></video>

		</div>
	<% end %>

<% end %>

app/views/menus/edit.html.erb
<div class='panel panel-default' class='menu_form'>
	<div class="panel-heading">메뉴 정보 수정</div>

	<%= render 'form' %>

</div>

<script type="text/javascript">
	document.getElementById("back_btn").href="<%= restaurant_menus_path %>"; 
</script>

app/views/menus/edit_photo.html.erb
<% @menu.photos.each_with_index do |photo, index| %>
  <div class="item <%= "active" if index == 0 %>">
    <%= image_tag photo.url(:large), :id => 'cropbox' %>
    <%= photo.id %>
    <%= link_to 'crop', edit_restaurant_menu_menu_photo_path(@menu.restaurant, @menu, photo.id) %>
  </div>
<% end %>

app/views/menus/home.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class='center'>
  <%= link_to image_tag('edit_menu.png'), 'menus/home', :class=>'main_btn_img' %>
  <%= link_to image_tag('new_menu.jpg'), new_restaurant_menu_path, :class=>'main_btn_img' %>
</div>

app/views/menus/index.html.erb
<div class='row'>
  <div class='col-md-3 menu-category'>
    <!-- Nav tabs -->
    <div class='panel panel-default'>
      <ul class="nav nav-tabs tabs-left" role="tablist" style="padding-top:0;">
        <div class='menu-category-header'>
          <li class='title'><%= t(:category_header) %></li>
        </div> 
        <% if @categories.blank? %>
          <li>
            <a href="#home" data-toggle="tab">기본메뉴</a>
          </li>
        <% else %>        
          <% @categories.each_with_index do |category, index| %>
            <li <% if index==0 %>class='active'<% end %>>
              <a href="#<%= category.name %>" data-toggle="tab">
                <%= category.name %>
              </a>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class='col-md-9 menu-list'>
    <div class="tab-content panel panel-default">

        <% if @categories.blank? %>
          <div class="tab-pane active" id="home">
            <div class='panel-body'>
              <div class='menu-header clearfix'>
                <h3 class="inline-header">기 본 메 뉴</h3>
              </div>
              <% @menus.each do |menu| %>
                <%= render :partial=>"menu_item", :locals=>{:menu => menu}  %>
              <% end %>
            </div>
          </div>

        <% else %>
          <% @categories.each_with_index do |category, index| %>
            <div class="tab-pane <% if index==0 %>active<% end %>" id="<%= category.name %>">
              <div class='panel-body'>
                <div class='menu-header clearfix'>
                  <h3 class="inline-header"><%= category.name %></h3>
                </div>

              <% @menus.each do |menu| %>
                <% if category.id == menu.category_id %>
                  <%= render :partial=>"menu_item", :locals=>{:menu => menu} %>
                <% end %>
              <% end %>
              </div>
            </div>
          <% end %>
        <% end %>

        <div id="detail_tap" role="tabpanel" class="section-tab tab-pane fade">

        </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>
  <% if @restaurant.user_id == current_user.id %>
    <div class='row'>
      <%= link_to t(:new_menu_button), new_restaurant_menu_path,
      :class=>'btn btn-primary col-md-2 right',
      :style=>'margin-right:15px;' %>
    </div>
  <% end %>
<% end %>

<%= render :partial=>"detail" %>

app/views/menus/new.html.erb
<div class='panel panel-default' class='menu_form'>
	<div class="panel-heading">신규 메뉴 등록</div>

	<%= render 'form' %>

</div>

<script type="text/javascript">
	document.getElementById("back_btn").href="<%= restaurant_menus_path %>"; 
</script>

app/views/menus/show.html.erb
<div class="page-header">
	<div class='row'>
		<div class='col-md-12'>
			<h1 class="title"><%= @menu.name %></h1>
			<h1 class="title" id='menu_name'></h1>
		</div>
	</div>
</div>

<div class = 'row'>
	<!-- 메뉴 사진 -->
	<div class = 'col-md-6'>
		<div id='photo_info' class="panel panel-default">
		  <div class="panel-body">
		    <%= render :partial=>"photo" %>
		  </div>
		</div>
	</div>

	<!-- 기타 정보 -->
	<div class='col-md-6'>
		<div id='menu-info' class="panel panel-default">
			<div class="panel-body">
				<li class="price" id='default_price' value="<%= @menu.price %>">
					<%= number_to_currency(@menu.price, :unit => "₩ ", precision: 0, format: '%u%n') %>
				</li>
				<li class="price" id="locale_price"></li>
			</div>
		  <div class="panel-footer">
		  	<%= @menu.description %>
			</div>
		</div>
		<div class='row'>
	  	<div class='col-xs-6'>
				<%= link_to '메뉴판 보기', restaurant_menus_path,
				:class=>'btn btn-primary',
		    :style=>'width:100%;' %>
	    </div>
	    <% if user_signed_in? %>
				<% if @restaurant.user_id == current_user.id %>
			    <div class='col-xs-6'>
						<%= link_to '수정', edit_restaurant_menu_path(@menu.restaurant, @menu),
						:class=>'btn btn-primary',
			      :style=>'width:100%;' %>
			    </div>
			  <% end %>
		  <% end %>
	  </div>
	</div>

</div>

<div>
	<%= render :partial=>'video' %>
</div>

<p style='display:none' id='real_price'><%= @menu.price %></p>

<%= render :partial=>'change_lang' %>