config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    match 'login' => 'devise/sessions#new', via: :get
    match 'login' => 'devise/sessions#create', via: :post
    match 'logout' => 'devise/sessions#destroy', via: :get
    match 'signup' => 'devise/registrations#new', via: :get
    match 'signup' => 'devise/registrations#create', via: :post
  end

  resources :restaurants do
    get 'menus/home' => 'menus#home'
    resources :menus do
      resources :menu_photos
    end
    resources :categories
    resources :comments
  end

  resources :user_sym_points
  
  root 'restaurants#index'
  post '' => 'welcome#login'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :restaurant

	def rand_photo
		menu_ids = self.restaurant.menus.map(&:id)

		selected_menu_id = menu_ids[Random.rand(menu_ids.count)]

		menu = Menu.find(selected_menu_id)
		menu.main_photo(:large)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_restaurant
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    # @comments = Comment.all
    @comments = @restaurants.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    # @comment = Comment.new(comment_params)
    @comment = @restaurant.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @restaurant, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      # @comment = Comment.find(params[:id])
      @comment = @restaurant.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      # params[:comment]
      params.require(:comment).permit(:user_email, :description, :star_point)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@restaurant, @comment]) do |f| %>
  <%= f.error_notification %>

  <% if user_signed_in? %>
  	<%= f.hidden_field :user_email, :value => current_user.email %>
  <% end %>

  <div class="form-inputs">
    <input id="input-21f" value="0" type="number" min=0 max=5 step=0.1 data-size="md", name='comment[star_point]'>
  	<%= f.input :description, input_html: { rows: 4 }, :label=>'리뷰' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<!-- Star Rating -->
<script>
  jQuery(document).ready(function () {
    $("#input-21f").rating({
        starCaptions: function(val) {
            return val;
        },
        starCaptionClasses: function(val) {
            if (val < 3) {
                return 'label label-danger';
            } else {
                return 'label label-success';
            }
        },
        hoverOnClear: false
    });
    
    $('#rating-input').rating({
          min: 0,
          max: 5,
          step: 1,
          size: 'lg',
          showClear: false
       });
       
    $('#btn-rating-input').on('click', function() {
        $('#rating-input').rating('refresh', {
            showClear:true, 
            disabled:true
        });
    });
    
    
    $('.btn-danger').on('click', function() {
        $("#kartik").rating('destroy');
    });
    
    $('.btn-success').on('click', function() {
        $("#kartik").rating('create');
    });
    
    $('#rating-input').on('rating.change', function() {
        alert($('#rating-input').val());
    });
    
    
    $('.rb-rating').rating({'showCaption':true, 'stars':'3', 'min':'0', 'max':'3', 'step':'1', 'size':'xs', 'starCaptions': {0:'status:nix', 1:'status:wackelt', 2:'status:geht', 3:'status:laeuft'}});
  });
</script>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="page-header">
  <h1>후기 등록   <small>별점을 선택해주세요</small></h1>
</div>
<%= render 'form' %>

<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>