config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    match 'login' => 'devise/sessions#new', via: :get
    match 'login' => 'devise/sessions#create', via: :post
    match 'logout' => 'devise/sessions#destroy', via: :get
    match 'signup' => 'devise/registrations#new', via: :get
    match 'signup' => 'devise/registrations#create', via: :post
  end

  resources :restaurants do
    get 'menus/home' => 'menus#home'
    resources :menus do
      resources :menu_photos
    end
    resources :categories
    resources :comments
  end

  resources :user_sym_points
  
  root 'restaurants#index'
  post '' => 'welcome#login'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus, dependent: :destroy
	has_many :categories, dependent: :destroy
	has_many :restaurant_photos, dependent: :destroy
  has_many :comments
  has_many :user_sym_points

  belongs_to :user

	def photos
  	self.restaurant_photos.order('seq')
  end

  def create_photos(photos)
    seq = self.photos.count

    photos.each do |p|
      seq = seq + 1
      self.restaurant_photos.create(:photo=>p, :seq=>seq)
    end
  end

  def main_photo(type)
    if self.restaurant_photos.order('seq').first
      self.restaurant_photos.order('seq').first.url(type)
    else
      "/assets/logo/restaurant#{RestaurantPhoto::PHOTO_STYLE[type]}.png"
    end
  end

  def week_days
    ret = []

    ret << (self.sun_d ? self.open_time.to_s(:time) : "Closed")
    ret << (self.mon_d ? self.open_time.to_s(:time) : "Closed")
    ret << (self.tue_d ? self.open_time.to_s(:time) : "Closed")
    ret << (self.wed_d ? self.open_time.to_s(:time) : "Closed")
    ret << (self.thu_d ? self.open_time.to_s(:time) : "Closed")
    ret << (self.fri_d ? self.open_time.to_s(:time) : "Closed")
    ret << (self.sat_d ? self.open_time.to_s(:time) : "Closed")

    ret
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @comments = @restaurant.comments.all

    @sum_star_point = 0

    @comments.each do |comment|
      @sum_star_point = @sum_star_point + comment.star_point
    end
    if @comments.count == 0
      @average_star_point = 0
    else
      @average_star_point = @sum_star_point / @comments.count
    end

    if user_signed_in?
      @user_sym_points = UserSymPoint.where(:restaurant_id => @restaurant.id, :user_id => current_user.id)
      # find_all_by_user_id(current_user.id)
      if @user_sym_points.blank?
        @user_sym_point = UserSymPoint.new
      end
    end
      @count = UserSymPoint.where(:restaurant_id => @restaurant.id).count
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    @restaurant.user_id = current_user.id

    respond_to do |format|
      if @restaurant.save
        unless params[:restaurant_photos].blank?
          @restaurant.create_photos(params[:restaurant_photos])          
        end
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update_attributes(restaurant_params)
        unless params[:restaurant_photos].blank?
          @restaurant.create_photos(params[:restaurant_photos])
        end
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      # params[:restaurant]
      params.require(:restaurant).permit(:name, :description, :r_code, :r_pwd, :open_time, :close_time, :mon_d, :tue_d, :wed_d, :thu_d, :fri_d, :sat_d, :sun_d, :postcode, :address, :x_pos, :y_pos, :phone)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<script src="http://dmaps.daum.net/map_js_init/postcode.js"></script>
<script type="text/javascript">
  function openDaumPostcode() {
    new daum.Postcode({
      oncomplete: function(data) {
        // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
        // 우편번호와 주소 정보를 해당 필드에 넣고, 커서를 상세주소 필드로 이동한다.
        document.getElementById('restaurant_postcode').value = data.postcode1 + data.postcode2;
        document.getElementById('restaurant_address').value = data.address;

        //전체 주소에서 연결 번지 및 ()로 묶여 있는 부가정보를 제거하고자 할 경우,
        //아래와 같은 정규식을 사용해도 된다. 정규식은 개발자의 목적에 맞게 수정해서 사용 가능하다.
        //var addr = data.address.replace(/(\s|^)\(.+\)$|\S+~\S+/g, '');
        //document.getElementById('addr').value = addr;

        get_position_from_address(data.address);

        document.getElementById('addr2').focus();
      }
    }).open();
  }
</script>

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">

  var map = null;
  var zoom_level = 16;
  function get_position_from_address(address){
    var geocoder = new google.maps.Geocoder();

    geocoder.geocode( {'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK){        
        $('#restaurant_x_pos').val(results[0].geometry.location.lng());
        $('#restaurant_y_pos').val(results[0].geometry.location.lat());
        $('#location_error_alert').hide();
        
        initialize_googlemap(results[0].geometry.location.lat(), results[0].geometry.location.lng());
      }else if(status == "ZERO_RESULTS"){
        $('#location_error_alert').show();
        if($('#restaurant_y_pos').val() == "" || $('#restaurant_y_pos').val() == null){
          //geocoding 결과가 없을 경우 서울의 좌표로 초기화 함.
          $('#restaurant_x_pos').val("126.986");
          $('#restaurant_y_pos').val("37.541");
        }
        initialize_googlemap($('#restaurant_y_pos').val(), $('#restaurant_x_pos').val());
      }
    });
  }

  function initialize_googlemap(latitude, longitude){
    latitude = latitude || $('#restaurant_y_pos').val() || "37.541";
    longitude = longitude || $('#restaurant_x_pos').val() || "126.986";

    var latlng = new google.maps.LatLng(latitude, longitude);
    var mapOptions = {
      zoom: zoom_level,
      center: latlng,
      navigationControl: true,
      navigationControlOptions: {
        style: google.maps.NavigationControlStyle.DEFAULT
      },
      scaleControl: true,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    map = new google.maps.Map(document.getElementById("gmap"),
        mapOptions);

    var marker = new google.maps.Marker({
      position: latlng,
      map: map
    });

    google.maps.event.addListener(map, 'click', function(event) {
      placeMarker(event.latLng, marker, map);
    });

    google.maps.event.addDomListener(window, 'resize', function() {
      map.setCenter(latlng);
    });

    google.maps.event.addListener(map, 'zoom_changed', function() {
      zoom_level = map.getZoom();
    });
    
    google.maps.event.addListenerOnce(map, 'idle', function() {
      google.maps.event.trigger(map, 'resize');
      map.setCenter(latlng);
    });

    $('#gmap_div').show();
  }

  function placeMarker(location, marker, map) {
    $('#restaurant_x_pos').val(location.lng());
    $('#restaurant_y_pos').val(location.lat());
    
    marker.setPosition(location);
    map.setCenter(location);
  }
</script>


<script type="text/javascript">
  $(function(){
    $('.pbtn_1').click(function(){
      $('#restaurant_form').submit();
    });

    $('.pbtn_2').click(function(){
      history.back();
    });
  })
</script>


<!-- 사진 미리보기 -->
<script type="text/javascript">
  function PreviewImage() {
    var reader = new FileReader();
    var files = document.getElementById("uploadImage").files;

    function readFile(index){
      if(index >= files.length) return;

      var file = files[index];
      reader.onload = function(e){
        $('#restaurant-photos-wrapper').append("<div class='col-md-3'><img class='img-responsive' src='" + e.target.result + "'/></div>");
        readFile(index + 1);
      }
      reader.readAsDataURL(file);
    }

    if(files.length > 0){
      readFile(0);
    }
  };

</script>

<%= simple_form_for(@restaurant, :html => {:multipart => true}) do |f| %>
  <%= f.error_notification %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">기본 정보 입력</h3>
    </div>
    <div class="panel-body">

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
          <label>음식점 이름</label>
        </div>
        <div class='col-md-6 col-xs-8 restaurant-form-input'>
          <%= f.text_field :name, :class=>'string optional form-control' %>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
          <label>사진</label>
        </div>
        <div class='col-md-4 restaurant-form-input'>
          <input id="uploadImage" class="form-control file" type="file" name="restaurant_photos[]" label="affe" onchange="PreviewImage();" accept="image/*" capture="camera" multiple>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
          <label>설명</label>
        </div>
        <div class='col-md-9 restaurant-form-input'>
          <textarea rows="5" class="text optional form-control" name="restaurant[description]" id="restaurant_description"><%= @restaurant.description %></textarea>
        </div>
      </div>

      <div class="form-inputs">
        <% if !@restaurant.photos.empty? %>
          <div class="row">
            <% @restaurant.photos.each do |p| %>
              <div class="col-md-4 restaurant-edit-photo">
                <%= image_tag p.photo.url(:medium), :class=>"img-responsive" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
        </div>
        <div class='col-md-9 restaurant-form-input'>
          <%= f.button :submit, :value=>t(:save_button), :class=>'btn btn-primary' %>
        </div>
      </div>

    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">시간 및 요일 정보 입력</h3>
    </div>
    <div class="panel-body">

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
          <label>오픈 시간</label>
        </div>
        <div class='col-md-4 restaurant-form-input'>
          <%= f.time_select :open_time, :default => {:hour => '9', :minute => '30'} %>
        </div>
        <div class='col-md-2 restaurant-form-label'>
          <label>클로즈 시간</label>
        </div>
        <div class='col-md-4 restaurant-form-input'>
          <%= f.time_select :close_time, :default => {:hour => '22', :minute => '00'} %>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
          <label>오픈 요일</label>
        </div>
        <div class='col-md-8 restaurant-form-input'>
          <table class="table bordered-table lined-table">
            <tbody class="centered">
              <tr>
                <% I18n.t("date.abbr_day_names").each_with_index do |day, idx| %>
                  <td class="day<%= idx %>"><%=  day %></td>
                <% end %>
              </tr>
              <tr>
                <td>
                  <input class="boolean optional" type="checkbox" value="1" name="restaurant[sun_d]" id="restaurant_sun_d">
                </td>
                <td>
                  <input class="boolean optional" type="checkbox" value="1" name="restaurant[mon_d]" id="restaurant_mon_d">
                </td>
                <td>
                  <input class="boolean optional" type="checkbox" value="1" name="restaurant[tue_d]" id="restaurant_tue_d">
                </td>
                <td>
                  <input class="boolean optional" type="checkbox" value="1" name="restaurant[wed_d]" id="restaurant_wed_d">
                </td>
                <td>
                  <input class="boolean optional" type="checkbox" value="1" name="restaurant[thu_d]" id="restaurant_thu_d">
                </td>
                <td>
                  <input class="boolean optional" type="checkbox" value="1" name="restaurant[fri_d]" id="restaurant_fri_d">
                </td>
                <td>
                  <input class="boolean optional" type="checkbox" value="1" name="restaurant[sat_d]" id="restaurant_sat_d">
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
        </div>
        <div class='col-md-9 restaurant-form-input'>
          <%= f.button :submit, :value=>t(:save_button), :class=>'btn btn-primary' %>
        </div>
      </div>

    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">위치 정보 입력</h3>
    </div>
    <div class="panel-body">

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
          <label>전화번호</label>
        </div>
        <div class='col-md-4 restaurant-form-input'>
          <input class="string tel optional form-control" type="tel" name="restaurant[phone]" id="restaurant_phone">
        </div>
      </div>

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
          <label>우편번호</label>
        </div>
        <div class='col-md-4 restaurant-form-input'>
          <input id="restaurant_postcode" type="number" class="form-control" readonly="true" value="<%= @restaurant.postcode unless @restaurant.postcode.nil? %>" name='restaurant[postcode]'>
        </div>
        <div class='col-md-4 restaurant-form-input'>
          <input type="button" onclick="openDaumPostcode()" class='btn btn-default' value='우편번호 찾기'>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
          <label>기본주소</label>
        </div>
        <div class='col-md-6 restaurant-form-input'>
          <input id="restaurant_address" type="text" class="form-control" readonly="true" value="<%= @restaurant.address unless @restaurant.address.nil? %>" name='restaurant[address]'>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
          <label>상세주소</label>
        </div>
        <div class='col-md-6 restaurant-form-input'>
          <input type="text" id="addr2" class="form-control">
        </div>
      </div>

      <div class='row' id="gmap_div" style="display: none;">
        <div class='col-md-2 restaurant-form-label'>
          <h3><span class="label label-danger">위치를 확인해주세요</span></h3>
        </div>
        <div class='col-md-8 restaurant-form-input'>
          <div id="gmap" style="width: 100%; height: 200px;"></div>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-2 restaurant-form-label'>
        </div>
        <div class='col-md-9 restaurant-form-input'>
          <%= f.button :submit, :value=>t(:save_button), :class=>'btn btn-primary' %>
        </div>
      </div>

    </div>
  </div>

  <%= f.input :x_pos, :as => :hidden, :id => 'restaurant_x_pos' %>
  <%= f.input :y_pos, :as => :hidden, :id => 'restaurant_y_pos' %>

<% end %>

app/views/restaurants/_location.html.erb
<% if @restaurant.x_pos.nil? %>
	<img src="http://placehold.it/577x428" alt="" style="width:100%;">
<% else %>
  <div id="gmap_div" style="display: none; width:100%; height:270px;">
    <div id="gmap" style="width: 100%; height: 100%;"></div>
  </div>
<% end %>
<% unless @restaurant.x_pos.nil? %>

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
	var map = null;
  var zoom_level = 16;
    
  
  window.onload = function() {
    // 여기가 ROOM의 위치
    var x_pos = <%= @restaurant.x_pos %>;
    var y_pos = <%= @restaurant.y_pos %>;
    initialize_googlemap(y_pos, x_pos);
  };

  function initialize_googlemap(latitude, longitude){
    var latlng = new google.maps.LatLng(latitude, longitude);
    var mapOptions = {
      zoom: zoom_level,
      center: latlng,
      navigationControl: true,
      navigationControlOptions: {
        style: google.maps.NavigationControlStyle.DEFAULT
      },
      scaleControl: true,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    map = new google.maps.Map(document.getElementById("gmap"),
        mapOptions);

    var marker = new google.maps.Marker({
      position: latlng,
      map: map
    });

    google.maps.event.addListener(map, 'click', function(event) {
      placeMarker(event.latLng, marker, map);
    });

    google.maps.event.addDomListener(window, 'resize', function() {
      map.setCenter(latlng);
    });

    google.maps.event.addListener(map, 'zoom_changed', function() {
      zoom_level = map.getZoom();
    });
    
    google.maps.event.addListenerOnce(map, 'idle', function() {
      google.maps.event.trigger(map, 'resize');
      map.setCenter(latlng);
    });

    $('#gmap_div').show();
  }

  function placeMarker(location, marker, map) {
    $('#restaurant_x_pos').val(location.lng());
    $('#restaurant_y_pos').val(location.lat());
    
    marker.setPosition(location);
    map.setCenter(location);
  }

  $('a#location_tab[data-toggle="tab"]').on('shown.bs.tab', function (e) {
    showmap();
  });
</script>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/new.html.erb
<div class="page-header">
  <h1>새로운 음식점 등록</h1>
</div>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<!-- Star Rating -->
<script>
  jQuery(document).ready(function () {
    $("#input-21f").rating({
        starCaptions: function(val) {
            return val;
        },
        starCaptionClasses: function(val) {
            if (val < 3) {
                return 'label label-danger';
            } else {
                return 'label label-success';
            }
        },
        hoverOnClear: false
    });
    
    $('#rating-input').rating({
          min: 0,
          max: 5,
          step: 1,
          size: 'lg',
          showClear: false
       });
       
    $('#btn-rating-input').on('click', function() {
        $('#rating-input').rating('refresh', {
            showClear:true, 
            disabled:true
        });
    });
    
    
    $('.btn-danger').on('click', function() {
        $("#kartik").rating('destroy');
    });
    
    $('.btn-success').on('click', function() {
        $("#kartik").rating('create');
    });
    
    $('#rating-input').on('rating.change', function() {
        alert($('#rating-input').val());
    });
    
    
    $('.rb-rating').rating({'showCaption':false, 'stars':'3', 'min':'0', 'max':'3', 'step':'1', 'size':'xs', 'starCaptions': {0:'status:nix', 1:'status:wackelt', 2:'status:geht', 3:'status:laeuft'}});
  });
</script>

<style type="text/css">
	.star-rating.rating-md.rating-disabled{
		float: left;
	}

	.menu-btns{
		margin-bottom: 20px;
	}

	.menu-btns .btn{
		width: 100%;
	}
</style>

<div class="page-header">
	<div class='row'>
		<div class='col-md-12'>
			<h1 class="title"><%= @restaurant.name %></h1>
			<input id="input-21f" value="<%= @average_star_point %>" type="number" min=0 max=5 step=0.1 data-size="md", data-show-clear='false' readonly="true">
		</div>
	</div>
</div>
	
<div class = 'row'>
	<!-- 음식점 사진 -->
	<div class = 'col-md-6'>
		<div id='photo_info' class="panel panel-default">
		  <div class="panel-body">
		    <%= render :partial=>"photo" %>
		  </div>
		  <div class="panel-footer">
		  	<div class='row' style='margin-bottom:0;'>
			  	<div class='col-xs-12'>	
			  		<h5 class="inline-header">
			  				이 작성자를 <%= @count %>명이 공감합니다.
		  			</h5>

		  			<!-- Uses 평가 -->
						<% if user_signed_in? %>
							<% if @user_sym_points.blank? %>
								<%= form_for(@user_sym_point, url: user_sym_points_path) do |f| %>
									  <%= f.hidden_field :restaurant_id, :value => @restaurant.id %>
									  <%= f.submit "공감", class: "btn btn-success right btn-sm" %>
								<% end %>
							<% else %>
								<% @user_sym_points.each do |sp| %>
									<%= link_to '취소', sp, method: :delete, class: "btn btn-danger right btn-sm"%>
								<% end %>
							<% end %>
						<% end %>
			  	</div>
				</div>
			</div>
		</div>
	</div>
	<!-- 음식점 정보 -->
  <div class ="col-md-6">
  	<div id="address_info" class="panel panel-default">
		  <div class="panel-body">
		  	<div class="menu-btns">
		  			<div class="row">
		  				<div class="col-xs-6 <% "col-xs-offset-6" if user_signed_in? %>">
		  					<%= link_to t(:go_to_menu), restaurant_menus_path(@restaurant.id), class: "btn btn-primary" %>
	  					</div>
	  					<div class="col-xs-6">
	  							<% if user_signed_in? %>
									  <% if @restaurant.user_id == current_user.id %>
									    <%= link_to '메뉴 분류 구성', restaurant_categories_path(@restaurant.id), class: "btn btn-default" %>
									  <% end %>
									<% end %>
  						</div>
		  			</div>
				</div>

		    <%= render :partial=>"location" %>
		    <div id='restaurant_info'>
		    	<div class="row margin-bottom10">
		    		<div class='col-xs-3'>
		    			<h4><span><%= t(:address_info) %></span></h4>
		    		</div>
		    		<div class='col-xs-9'>
		    			<h4>
		    				<%= @restaurant.address.gsub(/\(.*?\)/, '') %>
		    				<br><%= @restaurant.address[/\(.*?\)/] %>
		    			</h4>
		    		</div>
		    	</div>

		    	<div class="row no-bottom">
		    		<div class='col-xs-3'>
		    			<h4><span><%= t(:phone_info) %></span></h4>
		    		</div>
		    		<div class='col-xs-9'>
		    			<h4><%= @restaurant.phone %></h4>
		    		</div>
		    	</div>

		    </div>
		  </div>
		</div>
  </div>
</div>

<div class="row">
	<!-- 시간 / 요일 정보 -->
	<div class="col-md-12">
		<table class="table bordered-table lined-table">
			<thead>
				<tr>
					<th class="centered" colspan="7">
						<h4>Today &nbsp; <%= @restaurant.open_time.to_s(:time) %> ~ <%= @restaurant.close_time.to_s(:time) %></h4>
					</th>
				</tr>
			</thead>
			<tbody class="centered">
				<tr>
					<% I18n.t("date.abbr_day_names").each_with_index do |day, idx| %>
						<td class="day<%= idx %>"><%=  day %></td>
					<% end %>
				</tr>
				<tr>
					<% @restaurant.week_days.each do |wtime| %>
						<td>
							<%= wtime %>
						</td>
					<% end %>
				</tr>
			</tbody>
		</table>
	</div>
</div>


<div class='row'>
	<!-- 리뷰 Start -->
	<div class="col-md-12">
		<div class="review-header clearfix">
			<h4 class="inline-header"><%= t(:reviews_and_ratings) %></h4>
			<%= link_to t(:new_review_button), new_restaurant_comment_path(@restaurant), class: "btn btn-primary right" %>
		</div>
	</div>

	<div class='col-md-12'>
		<div class="row grid">

			<% @comments.each do |comment| %>
				<div class="col-md-3 grid-item">
					<div class="review-item">
						<div class="star-rate" style='width: 142px; margin: 0 auto;'>
							<input id="input-21f" type="number" class="rating" min=0 max=5 step=0.5 data-size="xs" readonly="true", data-show-clear='false' value='<%= comment.star_point %>' data-show-caption="false">
						</div>
						<div class="writer">
							<%= comment.user_email %>
						</div>

						<div class="review-photo">
							<%= image_tag comment.rand_photo, class: "img-responsive" %>
						</div>
						<div><%= comment.description %></div>
					</div>
				</div>
			<% end %>
					<!-- Test - Start -->
			<% @comments.each do |comment| %>
				<div class="col-md-3 grid-item">
					<div class="review-item">
						<div class="star-rate" style='width: 142px; margin: 0 auto;'>
							<input id="input-21f" type="number" class="rating" min=0 max=5 step=0.5 data-size="xs" readonly="true", data-show-clear='false' value='<%= comment.star_point %>' data-show-caption="false">
						</div>
						<div class="writer">
							<%= comment.user_email %>
						</div>

						<div class="review-photo">
							<%= image_tag comment.rand_photo, class: "img-responsive" %>
						</div>
						<div><%= comment.description %></div>
					</div>
				</div>
			<% end %>

			<% @comments.each do |comment| %>
				<div class="col-md-3 grid-item">
					<div class="review-item">
						<div class="star-rate" style='width: 142px; margin: 0 auto;'>
							<input id="input-21f" type="number" class="rating" min=0 max=5 step=0.5 data-size="xs" readonly="true", data-show-clear='false' value='<%= comment.star_point %>' data-show-caption="false">
						</div>
						<div class="writer">
							<%= comment.user_email %>
						</div>

						<div class="review-photo">
							<%= image_tag comment.rand_photo, class: "img-responsive" %>
						</div>
						<div><%= comment.description %></div>
					</div>
				</div>
			<% end %>
				<!-- Test End -->
		</div>
	</div>
</div>
<!-- 리뷰 End -->

<% if user_signed_in? %>
  <% if @restaurant.user_id == current_user.id %>
    <%= link_to '음식점 정보 수정', edit_restaurant_path(@restaurant), :class=>'btn btn-primary right' %>
  <% end %>
<% end %>

<script type="text/javascript">
	$(function(){
		$('.grid').masonry({
		  // options
		  percentPosition: true,
		  itemSelector: '.grid-item',
		  columnWidth: '.col-md-3'

		});
	});
</script>