config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    match 'login' => 'devise/sessions#new', via: :get
    match 'login' => 'devise/sessions#create', via: :post
    match 'logout' => 'devise/sessions#destroy', via: :get
    match 'signup' => 'devise/registrations#new', via: :get
    match 'signup' => 'devise/registrations#create', via: :post
  end

  resources :restaurants do
    get 'menus/home' => 'menus#home'
    resources :menus do
      resources :menu_photos
    end
    resources :categories
    resources :comments
  end

  resources :user_sym_points
  
  root 'restaurants#index'
  post '' => 'welcome#login'

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :restaurant
	
	has_many :menus
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_restaurant
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    # @categories = Category.all
    @categories = @restaurant.categories.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    # @category = Category.new
    @category = @restaurant.categories.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    # @category = Category.new(category_params)
    @category = @restaurant.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category.restaurant, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category.restaurant, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to [@category.restaurant, @category], notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      # params[:category]
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for([@restaurant, @category]) do |f| %>
  <%= f.error_notification %>

  <div class="panel-body">
	  <div class='row'>
	    <div class='col-md-2 menu-form-label'>
	      <label>카테고리 명</label>
	    </div>
	    <div class='col-md-6 col-xs-8 menu-form-input'>
	      <%= f.text_field :name, :class=>'string optional form-control' %>
	    </div>
	  </div>
	

	  <div class='row'>
	    <div class='col-md-2 menu-form-label'>
	    </div>
	    <div class='col-md-9 menu-form-input'>
	      <%= f.button :submit, :value=>'저장', :class=>'btn btn-primary' %>
	    </div>
	  </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="page-header">
  <div class='row'>
    <div class='col-md-12'>
      <h1 class="title">메뉴 카테고리 구성</h1>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">카테고리 목록</h3>
  </div>
  <div class="panel-body">
    <% @categories.each do |category| %>
          <div class='row'>
            <div class='col-xs-3' style='text-align:right;'>
              <%= category.name %>
            </div>
            <div class='col-xs-2'>
              <%= link_to '수정', edit_restaurant_category_path(category.restaurant, category), class: "btn btn-primary" %>
            </div>
            <div class='col-xs-2'>        
              <%= link_to '삭제', [category.restaurant, category], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
  </div>
</div>

<div class='row'>
  <%= link_to '카테고리 추가', new_restaurant_category_path,
  :class=>'btn btn-primary col-md-2 right',
  :style=>'margin-right:15px;' %>
</div>

app/views/categories/new.html.erb
<div class='panel panel-default' class='menu_form'>
	<div class="panel-heading">메뉴 카테고리 추가</div>

	<%= render 'form' %>

</div>

<%= link_to 'Back', restaurant_categories_path(@restaurant.id),
:style=>'display:none;' %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

<%= link_to 'Edit', edit_restaurant_category_path(@category.restaurant, @category) %> |
<%= link_to 'Back', restaurant_categories_path(@restaurant.id) %>